dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

branches:
  only:
    - master

before_script:
  - sudo apt-get install 
  - sudo apt-get -qq update
  - sudo apt-get -y install python3 libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxext-dev

install:
  - wget -O vulkansdk.run https://sdk.lunarg.com/sdk/download/1.1.73.0/linux/vulkansdk-linux-x86_64-1.1.73.0.run
  - chmod ugo+x vulkansdk.run
  - ./vulkansdk.run
  - export VK_SDK_PATH=$TRAVIS_BUILD_DIR/VulkanSDK/1.1.73.0/x86_64
  - export VULKAN_SDK=$TRAVIS_BUILD_DIR/VulkanSDK/1.1.73.0/x86_64

script:
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - gcc -v && g++ -v && cmake --version
  - sed -i 's,git@github.com:,https://github.com/,g' CMakeLists.txt
  - cmake -H. -Bbuild_linux_x86_64
  - cd build_linux_x86_64
  - make

notifications:
  email:
    recipients:
      - vlad.serhiienko@gmail.com
    on_success: change
    on_failure: always
