version: '{build}'
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
platform: x64
configuration: Release
init:
  - git config --global core.autocrlf true
install:
  # - ps: Get-ChildItem "dependencies" -Recurse | Remove-Item
  # - ps: Get-ChildItem "build_msvc" -Recurse | Remove-Item
  - ps: (Get-Content CMakeLists.txt).replace("git@github.com:","https://github.com/") | Set-Content CMakeLists.txt
  - ps: md installs
  - ps: cd installs
  - ps: Start-FileDownload "https://sdk.lunarg.com/sdk/download/1.1.73.0/windows/VulkanSDK-1.1.73.0-Installer.exe" "VulkanSDK.exe"
  - ps: Start-Process -FilePath "VulkanSDK.exe" /S -Wait
  - ps: cd ..

environment:
  VK_SDK_PATH: "C:/VulkanSDK/1.1.73.0"
before_build:
  - cmake -G "Visual Studio 15 2017 Win64" -Bbuild_msvc -H. -DBUILD_FOLDER_SUFFIX:STRING=build_msvc
build_script:
  - ps: msbuild build_msvc/ViewerSdl.sln /t:ViewerSdl /p:Configuration="Release"
  # - ps: cd dependencies/shaderc
  # - ps: python.exe utils/git-sync-deps
  # - ps: cd ../..
  # - ps: msbuild build_msvc/Viewer.sln /t:ShaderPipeline /p:Configuration="Release"
notifications:
- provider: Email
  to:
    - vlad.serhiienko@gmail.com
  subject: Viewer build {{buildVersion}} - {{status}}
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true